### PR TITLE
Feature list indexing.py

### PR DESCRIPTION
**Pull request by poornima-ezhilmathi**

### CODE REVIEW

**Review by leocyriac — CHANGES_REQUESTED** [review]
List is not correctly formed.

image

**Comment by poornima-ezhilmathi** [comment]
> List is not correctly formed.
> 
> image


Sorry Leo, I checked with only single character.  I have tried like this. please review


Enter the number of sub list and the value in each list:3
Enter a value and press enter01
Enter a value and press enterJhon
Enter a value and press enterjhon@gmail.com
Enter a value and press enter02
Enter a value and press enterJordan
Enter a value and press enterjordon@gmail.com
Enter a value and press enter03
Enter a value and press enterSarah
Enter a value and press entersarah@gmail.com
You entered : '[['01', 'Jhon', 'jhon@gmail.com'], ['02', 'Jordan', 'jordon@gmail.com'], ['03', 'Sarah', 'sarah@gmail.com']]'

**Review by leocyriac — CHANGES_REQUESTED** [review]
Values are hardcoded. Please form the list from command prompt. it doesn't need to be a nested list. But a simple list.

**Review by leocyriac — APPROVED** [review]
Looks good, please merge.

**Pull request closed without merging**
